name: Save New Version to Process BP Platform

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+"

jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send version info to platform
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: "https://8000-trilogygrou-processbppl-mdvd7epypkd.ws.trilogy.devspaces.com/templates/add_version/"
          method: "POST"
          customHeaders: '{"Authorization": "Token ${{ secrets.USER_TOKEN }}"}'
          data: '{ "ref_name": "${{ github.ref_name }}", "repository": "$GITHUB_REPOSITORY" }'
